### PR TITLE
 feat: create environment for every PR using Uffizzi

### PR DESCRIPTION
**Pull request by daramayis**
This PR is a part of https://github.com/fonoster/fonoster/issues/431 and helps demonstrate Uffizzi integration with **Rox**. 

This will help create preview environments on all of **Rox** Pull Requests and help contributors including the maintainers iterate faster on their PRs. 
I have created a PR over https://github.com/daramayis/f-rox/pull/1#issuecomment-1318406270 to show what it looks like to have a preview environment deployed against your PR.

You can check out the preview over [here](https://app.uffizzi.com/github.com/daramayis/f-rox/pull/1) as well.

@waveywaves

### CODE REVIEW

**Comment by psanders** [comment]
@YuriCodes can you take a look at this PR sometime today or tomorrow? I will do the same.

**Review by YuriCodes — DISMISSED** [review]
it'll be a good addition to have

**Comment by waveywaves** [comment]
Once this PR is merged, we can review the previews right after @psanders @YuriCodes

**Comment by psanders** [comment]
I had a first pass at this and was unable to connect to the service. I will take another look at it next week:

Screenshot 2022-11-25 at 11 10 19 AM

**Comment by daramayis** [comment]
@psanders could you please provide the cURL for this API — so I will check?

**Comment by waveywaves** [comment]
@psanders can you send the steps to test the preview ?

**Comment by psanders** [comment]
Hey @daramayis @waveywaves 

You cand send a request as follows:

```bash
curl -X POST "http://localhost:3000" \
  -H 'Content-Type: application/json' \
  -d '{"accessKeyId":"REDACTED","appRef":"REDACTED","callerId":"ACCT Test","callerNumber":"testacct","dialbackEnpoint":"REDACTED","metadata":{},"number":"REDACTED","selfEndpoint":"https://77e3-47-132-130-31.ngrok.io","sessionId":"1669575016.1","sessionToken":"REDACTED"}'
```

You will see an error on the app side, but know that the server is responding:

```
error: 16 UNAUTHENTICATED: invalid authentication {"accessKeyId":"REDACTED","eventType":"app"}
```

**Review by psanders — APPROVED** [review]

**Pull request merged**
